version: '3'
services:
    left_client:
        image: telegraf:1.18
        container_name: left_client
        volumes:
            - "/Users/samdillard/demos/iot/mqtt/mqtt-demo/telegraf/left.conf:/etc/telegraf/telegraf.conf"
        depends_on:
            - broker

    right_client:
        image: telegraf:1.18
        container_name: right_client
        volumes:
            - "/Users/samdillard/demos/iot/mqtt/mqtt-demo/telegraf/right.conf:/etc/telegraf/telegraf.conf"
        environment:
            - INFLUX_HOST=${INFLUX_HOST}
            - INFLUX_ORG=${INFLUX_ORG}
            - INFLUX_TOKEN=${INFLUX_TOKEN}
        depends_on: 
            - broker
            - left_client

    broker:
        # image: eclipse-mosquitto:latest
        image: hivemq/hivemq4
        container_name: broker
        ports:
            - "1883:1883"
            - "8080:8080"
    
    influxdb:
        image: influxdb:2.0.7
        container_name: influxd
        volumes:
            - "/Users/samdillard/demos/iot/mqtt/mqtt-demo/influxdb/data:/var/lib/.influxdbv2"
        environment:
            - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USERNAME}
            - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PASSWORD}
            - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG}
            - DOCKER_INFLUXDB_INIT_BUCKET=mqtt
            - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_TOKEN}
        ports:
            - "8086:8086"

    influx_cli:
        image: influxdb:2.0.7
        container_name: influx_cli
        environment:
            - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USERNAME}
            - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PASSWORD}
            - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG}
            - DOCKER_INFLUXDB_INIT_BUCKET=mqtt
            - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_TOKEN}
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
        depends_on:
            - influxd
        # override entrypoint to configure InfluxDB (and install tasks?) -- container shuts down after this
        entrypoint: influx setup --bucket mqtt -t ${INFLUX_TOKEN} -o ${INFLUX_ORG} --username=${INFLUX_USERNAME} --password=${INFLUX_PASSWORD} --host=http://influxd:8086 -f --skip-verify


