from(bucket: "mqtt")
    |> range(start: -10m)
    |> filter(fn: (r) => r._measurement == "cpu")
    |> filter(fn: (r) => r.host == "{device_id}")
    |> filter(fn: (r) => r.cpu == "cpu-total")
    |> filter(fn: (r) => r._field == "usage_user")
    |> mean()